version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: devopsdemo-backend:local
    container_name: devops-backend
    ports:
      - "5000:5000"
    networks:
      - devops-net

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: devopsdemo-frontend:local
    container_name: devops-frontend
    ports:
      - "3000:3000"
    networks:
      - devops-net
    # Wait for backend to be healthy before starting frontend
    depends_on:
      - backend

networks:
  devops-net:
    driver: bridge
