version: '3.8'
services:
  backend:
    container_name: devops-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    networks:
      - devops-net

  frontend:
    container_name: devops-frontend
    ports:
      - "80:80"
    # Wait for backend to be healthy before starting frontend
    depends_on:
      - backend
    networks:
      - devops-net


networks:
  devops-net:
    driver: bridge
