name: Validate Secrets
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Show masked secrets usage
        run: |
          echo "Host: ${{ secrets.VM_HOST }}"
          echo "User length: $(echo -n '${{ secrets.VM_USER }}' | wc -c)"
          echo "Key lines: $(echo '${{ secrets.VM_SSH_KEY }}' | wc -l)"
      - name: Test SSH connectivity
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Connected OK"
            uname -a
            docker version || echo "Docker not installed"